// Generated MCP server templates

import 'package:mcp_generator/builder/schema_builder.dart';

/// Generates stdio server code from tool definitions using dart_mcp.
class StdioTemplate {
  static String generate(
    List<Map<String, dynamic>> tools,
    String libraryName,
    String inputPath,
  ) {
    final importPath =
        'package:mcp_$libraryName${inputPath.replaceAll('lib', '')}';

    final toolRegistrations = tools
        .map((t) {
          final name = t['name'] as String;
          final schema = SchemaBuilder.buildObjectSchema(
            (t['parameters'] as List<Map<String, dynamic>>? ?? []),
          );
          return '''
    registerTool(
      Tool(
        name: '$name',
        description: '${t['description'] ?? 'Tool $name'}',
        inputSchema: $schema,
      ),
      _$name,
    );''';
        })
        .join('\n');

    final toolHandlers = tools
        .map((t) {
          final name = t['name'] as String;
          final params = t['parameters'] as List<Map<String, dynamic>>? ?? [];
          final paramExtractions = params
              .map((p) {
                final paramName = p['name'] as String;
                final paramType = p['type'] as String;
                return "    final $paramName = request.arguments!['$paramName'] as ${_dartType(paramType)};";
              })
              .join('\n');

          final isAsync = t['isAsync'] == true;
          final className = t['className'] as String?;
          final isStatic = t['isStatic'] == true;

          String call;
          if (className != null && isStatic) {
            call = isAsync
                ? 'await lib.$className.$name(${_callArgs(params)})'
                : 'lib.$className.$name(${_callArgs(params)})';
          } else if (className != null) {
            call = isAsync
                ? 'await lib.$className().$name(${_callArgs(params)})'
                : 'lib.$className().$name(${_callArgs(params)})';
          } else {
            call = isAsync
                ? 'await lib.$name(${_callArgs(params)})'
                : 'lib.$name(${_callArgs(params)})';
          }

          return '''
  FutureOr<CallToolResult> _$name(CallToolRequest request) async {
$paramExtractions
    final result = $call;
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }''';
        })
        .join('\n');

    return '''
// Generated MCP stdio server
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;

import 'package:dart_mcp/server.dart';
import 'package:dart_mcp/stdio.dart';

import '$importPath' as lib;

void main() {
  MCPServerWithTools(stdioChannel(input: io.stdin, output: io.stdout));
}

base class MCPServerWithTools extends MCPServer with ToolsSupport {
  MCPServerWithTools(super.channel)
    : super.fromStreamChannel(
        implementation: Implementation(
          name: 'mcp-server',
          version: '1.0.0',
        ),
        instructions: 'Auto-generated MCP server',
      ) {
$toolRegistrations
  }

$toolHandlers

  String _serializeResult(dynamic result) {
    if (result == null) return 'null';
    try {
      if (result is List) {
        final items = result.map((e) {
          if (e == null) return null;
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
          return e.toString();
        }).where((e) => e != null).toList();
        return jsonEncode(items);
      }
      final toJson = result.toJson;
      if (toJson != null && toJson is Function) return jsonEncode(toJson());
      return result.toString();
    } catch (_) {
      return result.toString();
    }
  }
}
''';
  }

  static String _callArgs(List<Map<String, dynamic>> params) {
    return params
        .map((p) {
          final name = p['name'] as String;
          final isNamed = p['isNamed'] == true;
          return isNamed ? '$name: $name' : name;
        })
        .join(', ');
  }

  static String _dartType(String type) {
    if (type.startsWith('List<')) return type;
    switch (type) {
      case 'String':
      case 'int':
      case 'double':
      case 'bool':
        return type;
      default:
        return 'dynamic';
    }
  }
}

/// Generates HTTP server code from tool definitions using dart_mcp.
class HttpTemplate {
  static String generate(
    List<Map<String, dynamic>> tools,
    int port,
    String libraryName,
    String inputPath,
  ) {
    final importPath =
        'package:mcp_$libraryName${inputPath.replaceAll('lib', '')}';

    final toolRegistrations = tools
        .map((t) {
          final name = t['name'] as String;
          final schema = SchemaBuilder.buildObjectSchema(
            (t['parameters'] as List<Map<String, dynamic>>? ?? []),
          );
          return '''
    registerTool(
      Tool(
        name: '$name',
        description: '${t['description'] ?? 'Tool $name'}',
        inputSchema: $schema,
      ),
      _$name,
    );''';
        })
        .join('\n');

    final toolHandlers = tools
        .map((t) {
          final name = t['name'] as String;
          final params = t['parameters'] as List<Map<String, dynamic>>? ?? [];
          final paramExtractions = params
              .map((p) {
                final paramName = p['name'] as String;
                final paramType = p['type'] as String;
                return "    final $paramName = request.arguments!['$paramName'] as ${_dartType(paramType)};";
              })
              .join('\n');

          final isAsync = t['isAsync'] == true;
          final className = t['className'] as String?;
          final isStatic = t['isStatic'] == true;

          String call;
          if (className != null && isStatic) {
            call = isAsync
                ? 'await lib.$className.$name(${_callArgs(params)})'
                : 'lib.$className.$name(${_callArgs(params)})';
          } else if (className != null) {
            call = isAsync
                ? 'await lib.$className().$name(${_callArgs(params)})'
                : 'lib.$className().$name(${_callArgs(params)})';
          } else {
            call = isAsync
                ? 'await lib.$name(${_callArgs(params)})'
                : 'lib.$name(${_callArgs(params)})';
          }

          return '''
  FutureOr<CallToolResult> _$name(CallToolRequest request) async {
$paramExtractions
    final result = $call;
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }''';
        })
        .join('\n');

    return '''
// Generated MCP HTTP server
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;

import 'package:dart_mcp/server.dart';
import 'package:dart_mcp/stdio.dart';

import '$importPath' as lib;

void main() {
  MCPServerWithTools(stdioChannel(input: io.stdin, output: io.stdout));
}

base class MCPServerWithTools extends MCPServer with ToolsSupport {
  MCPServerWithTools(super.channel)
    : super.fromStreamChannel(
        implementation: Implementation(
          name: 'mcp-server',
          version: '1.0.0',
        ),
        instructions: 'Auto-generated MCP server on port $port',
      ) {
$toolRegistrations
  }

$toolHandlers

  String _serializeResult(dynamic result) {
    if (result == null) return 'null';
    try {
      if (result is List) {
        final items = result.map((e) {
          if (e == null) return null;
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
          return e.toString();
        }).where((e) => e != null).toList();
        return jsonEncode(items);
      }
      final toJson = result.toJson;
      if (toJson != null && toJson is Function) return jsonEncode(toJson());
      return result.toString();
    } catch (_) {
      return result.toString();
    }
  }
}
''';
  }

  static String _callArgs(List<Map<String, dynamic>> params) {
    return params
        .map((p) {
          final name = p['name'] as String;
          final isNamed = p['isNamed'] == true;
          return isNamed ? '$name: $name' : name;
        })
        .join(', ');
  }

  static String _dartType(String type) {
    if (type.startsWith('List<')) return type;
    switch (type) {
      case 'String':
      case 'int':
      case 'double':
      case 'bool':
        return type;
      default:
        return 'dynamic';
    }
  }
}
