// Generated MCP stdio server
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;

import 'package:dart_mcp/server.dart';
import 'package:dart_mcp/stdio.dart';

import 'package:mcp_example/src/user.dart' as lib;

void main() {
  MCPServerWithTools(stdioChannel(input: io.stdin, output: io.stdout));
}

base class MCPServerWithTools extends MCPServer with ToolsSupport {
  MCPServerWithTools(super.channel)
    : super.fromStreamChannel(
        implementation: Implementation(
          name: 'mcp-server',
          version: '1.0.0',
        ),
        instructions: 'Auto-generated MCP server',
      ) {
    registerTool(
      Tool(
        name: 'createUser',
        description: 'Create a new user',
        inputSchema: Schema.object(
    properties: {
      'name': Schema.string(),
      'email': Schema.string(),
    },
  ),
      ),
      _createUser,
    );
    registerTool(
      Tool(
        name: 'getUser',
        description: 'Get user by ID',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
      ),
      _getUser,
    );
    registerTool(
      Tool(
        name: 'listUsers',
        description: 'List all users',
        inputSchema: Schema.object(),
      ),
      _listUsers,
    );
    registerTool(
      Tool(
        name: 'deleteUser',
        description: 'Delete a user',
        inputSchema: Schema.object(
    properties: {
      'id': Schema.int(),
    },
    required: ['id'],
  ),
      ),
      _deleteUser,
    );
    registerTool(
      Tool(
        name: 'searchUsers',
        description: 'Search users by query',
        inputSchema: Schema.object(
    properties: {
      'query': Schema.string(),
    },
    required: ['query'],
  ),
      ),
      _searchUsers,
    );
  }

  FutureOr<CallToolResult> _createUser(CallToolRequest request) async {
    final name = request.arguments!['name'] as String;
    final email = request.arguments!['email'] as String;
    final result = await lib.UserStore.createUser(name: name, email: email);
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }
  FutureOr<CallToolResult> _getUser(CallToolRequest request) async {
    final id = request.arguments!['id'] as int;
    final result = await lib.UserStore.getUser(id);
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }
  FutureOr<CallToolResult> _listUsers(CallToolRequest request) async {

    final result = await lib.UserStore.listUsers();
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }
  FutureOr<CallToolResult> _deleteUser(CallToolRequest request) async {
    final id = request.arguments!['id'] as int;
    final result = await lib.UserStore.deleteUser(id);
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }
  FutureOr<CallToolResult> _searchUsers(CallToolRequest request) async {
    final query = request.arguments!['query'] as String;
    final result = await lib.UserStore.searchUsers(query);
    return CallToolResult(
      content: [TextContent(text: _serializeResult(result))],
    );
  }

  String _serializeResult(dynamic result) {
    if (result == null) return 'null';
    try {
      if (result is List) {
        final items = result.map((e) {
          if (e == null) return null;
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
          return e.toString();
        }).where((e) => e != null).toList();
        return jsonEncode(items);
      }
      final toJson = result.toJson;
      if (toJson != null && toJson is Function) return jsonEncode(toJson());
      return result.toString();
    } catch (_) {
      return result.toString();
    }
  }
}
